FROM websphere-liberty:microProfile2

USER root
RUN apt-get update \
  && apt-get install -qq -y --no-install-recommends \
    software-properties-common \
    python-software-properties \
  && add-apt-repository ppa:openjdk-r/ppa \
  && apt-get update \
  && apt-get install -qq -y --no-install-recommends \
    autoconf \
    ca-certificates \
    ccache \
    cmake \
    cpio \
    file \
    git \
    git-core \
    libasound2-dev \
    libcups2-dev \
    libdwarf-dev \
    libelf-dev \
    libfontconfig \
    libfreetype6-dev \
    libnuma-dev \
    libx11-dev \
    libxext-dev \
    libxrender-dev \
    libxt-dev \
    libxtst-dev \
    make \
    openjdk-7-jdk \
    pkg-config \
    realpath \
    ssh \
    unzip \
    wget \
    zip \
  && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
 && apt-get install -qq -y --no-install-recommends \
    automake \
    curl \
    libssl-dev \
    libtool \
    build-essential \
    autoconf \
    pkg-config \
 && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
 && add-apt-repository ppa:ubuntu-toolchain-r/test -y \
 && apt-get update \
 && apt-get install -qq -y --no-install-recommends gcc-7 g++-7 \
 && rm -rf /var/lib/apt/lists/*

# JITaaS needs to be built with a newer GCC
RUN ln -sf /usr/bin/g++ /usr/bin/c++ \
 && ln -sf /usr/bin/g++-7 /usr/bin/g++ \
 && ln -sf /usr/bin/gcc /usr/bin/cc \
 && ln -sf /usr/bin/gcc-7 /usr/bin/gcc

# Install protobuf 3.5.1
WORKDIR /
RUN wget https://github.com/protocolbuffers/protobuf/releases/download/v3.5.1/protobuf-cpp-3.5.1.tar.gz \
 && tar -xvzf protobuf-cpp-3.5.1.tar.gz \
 && cd protobuf-3.5.1 \
 && ./configure && make && make install && ldconfig \
 && rm -rf /protobuf-3.5.1 && rm -rf /protobuf-cpp-3.5.1.tar.gz

COPY sdk /opt/ibm/sdk

RUN rm -rf /opt/ibm/java

RUN mv /opt/ibm/sdk /opt/ibm/java

ENV JAVA_HOME="/opt/ibm/java"
ENV JVM_ARGS="-XX:JITaaSClient:server=jitaas_server_microservice,port=38400 -Xjit:dontDowngradeToCold,sampleThreshold=0,scorchingSampleThreshold=0 -XX:+UseContainerSupport"
