acmeair-booking-db:
  container_name: acmeair-booking-db
  image: mongo
  net: ${NETWORK}

acmeair-customer-db:
  container_name: acmeair-customer-db
  image: mongo
  net: ${NETWORK}

acmeair-flight-db:
  container_name: acmeair-flight-db
  image: mongo
  net: ${NETWORK}

acmeair-nginx1:
  container_name: acmeair-nginx1
  net: ${NETWORK}
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/public
  volumes_from:
    - acmeair-mainservice-java
    - acmeair-authservice-java
    - acmeair-bookingservice-java
    - acmeair-customerservice-java
    - acmeair-flightservice-java
  mem_limit: 50m
  cpuset: 5,6,8
  cpus: 1

acmeair-mainservice-java:
  container_name: acmeair-mainservice-java
  dockerfile: Dockerfile-base
  net: ${NETWORK}
  build: ../acmeair-mainservice-java/
  environment:
    - LICENSE=accept
    - JVM_ARGS="-XX:+UseContainerSupport -Xjit:sampleThreshold=0"
  mem_limit: 50m
  memswap_limit: 50m
  cpuset: 0
  cpus: 1

acmeair-authservice-java:
  container_name: acmeair-authservice-java
  dockerfile: Dockerfile-base
  net: ${NETWORK}
  build: ../acmeair-authservice-java/
  environment:
    - LICENSE=accept
    - JVM_ARGS="-XX:+UseContainerSupport -Xjit:sampleThreshold=0"
  mem_limit: 50m
  memswap_limit: 50m
  cpuset: 1
  cpus: 1

acmeair-bookingservice-java:
  container_name: acmeair-bookingservice-java
  dockerfile: Dockerfile-base
  net: ${NETWORK}
  build: ../acmeair-bookingservice-java/
  environment:
    - LICENSE=accept
    - MONGO_HOST=acmeair-booking-db
    - JVM_ARGS="-XX:+UseContainerSupport -Xjit:sampleThreshold=0"
  volumes_from:
    - acmeair-booking-db
  mem_limit: 50m
  memswap_limit: 50m
  cpuset: 2
  cpus: 1

acmeair-customerservice-java:
  container_name: acmeair-customerservice-java
  dockerfile: Dockerfile-base
  net: ${NETWORK}
  build: ../acmeair-customerservice-java/
  environment:
    - LICENSE=accept
    - MONGO_HOST=acmeair-customer-db
    - JVM_ARGS="-XX:+UseContainerSupport -Xjit:sampleThreshold=0"
  volumes_from:
    - acmeair-customer-db
  mem_limit: 50m
  memswap_limit: 50m
  cpuset: 3
  cpus: 1

acmeair-flightservice-java:
  container_name: acmeair-flightservice-java
  dockerfile: Dockerfile-base
  net: ${NETWORK}
  build: ../acmeair-flightservice-java/
  environment:
    - LICENSE=accept
    - MONGO_HOST=acmeair-flight-db
    - JVM_ARGS="-XX:+UseContainerSupport -Xjit:sampleThreshold=0"
  volumes_from:
    - acmeair-flight-db
  mem_limit: 50m
  memswap_limit: 50m
  cpuset: 4
  cpus: 1
 
